# Generated by Django 2.2.4 on 2019-08-04 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escola', models.CharField(max_length=255, verbose_name='Nome da Escola')),
                ('endereco_escola', models.CharField(max_length=255, verbose_name='Endereço da Escola')),
                ('telefone_escola', models.CharField(max_length=12, verbose_name='Telefone da Escola')),
                ('email_escola', models.EmailField(max_length=255, unique=True, verbose_name='E-mail da Escola')),
                ('rede_ensino', models.CharField(choices=[('Estadual', 'Estadual'), ('Municipal', 'Municipal'), ('Federal', 'Federal'), ('Particular', 'Particular'), ('Outra', 'Outra')], max_length=255, verbose_name='Rede de Ensino da Escola')),
                ('tipo_ensino', models.CharField(choices=[('Ensino Fundamental', 'Ensino Fundamental'), ('Ensino Médio', 'Ensino Médio'), ('Ambos', 'Ambos')], max_length=255, verbose_name='Tipo de Ensino da Escola')),
                ('codigo_acesso', models.CharField(max_length=255, unique=True, verbose_name='Registre o código de acesso')),
                ('data_requisicao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_parceiro', models.CharField(choices=[('Pessoa', 'Pessoa'), ('Empresa/Ong', 'Empresa/Ong')], max_length=255, verbose_name='Selecione o tipo de contato')),
                ('nome_parceiro', models.CharField(max_length=255, verbose_name='Nome')),
                ('email_parceiro', models.EmailField(max_length=255, verbose_name='Email')),
                ('telefone_parceiro', models.CharField(max_length=12, verbose_name='Telefone')),
                ('mensagem_parceiro', models.TextField(verbose_name='Escreva sua mensagem!')),
                ('data_mensagem', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=255, verbose_name='Nome do Aluno')),
                ('sobrenome_aluno', models.CharField(max_length=255, verbose_name='Sobrenome do Aluno')),
                ('nascimento_aluno', models.DateField(verbose_name='Data de Nascimento do Aluno')),
                ('idade_aluno', models.PositiveIntegerField(verbose_name='Idade do Aluno')),
                ('genero_aluno', models.CharField(max_length=255, verbose_name='Gênero do Aluno')),
                ('turma_aluno', models.CharField(choices=[('5 SERIE', '5 SERIE'), ('6 SERIE', '6 SERIE'), ('7 SERIE', '7 SERIE'), ('8 SERIE', '8 SERIE'), ('1 ANO', '1 ANO'), ('2 ANO', '2 ANO'), ('3 ANO', '3 ANO')], max_length=255, verbose_name='Turma do Aluno')),
                ('pontuacao_aluno', models.PositiveIntegerField(default=0, verbose_name='Pontuação do Aluno')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualização', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Escola')),
            ],
        ),
    ]
