# Generated by Django 2.2.4 on 2019-08-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='senha_acesso',
            field=models.CharField(default=1, max_length=12, verbose_name='Registre a senha de acesso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='escola',
            name='codigo_acesso',
            field=models.CharField(max_length=12, verbose_name='Registre o código de acesso'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='email_escola',
            field=models.EmailField(max_length=255, verbose_name='Email da Escola'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='rede_ensino',
            field=models.CharField(max_length=255, verbose_name='Rede de Ensino'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='tipo_ensino',
            field=models.CharField(max_length=255, verbose_name='Tipo de Ensino'),
        ),
    ]
