# Generated by Django 2.2.4 on 2019-08-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190804_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='codigo_acesso',
            field=models.CharField(max_length=12, unique=True, verbose_name='Código de acesso'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='endereco_escola',
            field=models.CharField(max_length=255, verbose_name='Endereço da Escola'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='senha_acesso',
            field=models.CharField(max_length=12, verbose_name='Senha de acesso'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='telefone_escola',
            field=models.CharField(max_length=12, unique=True, verbose_name='Número de Telefone'),
        ),
    ]
