# Generated by Django 2.2.4 on 2019-08-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190805_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='telefone_escola',
            field=models.CharField(error_messages={'unique': 'telefone meo'}, max_length=12, unique=True, verbose_name='Número de Telefone'),
        ),
    ]
