# Generated by Django 2.2.4 on 2019-08-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190808_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='confirmar_senha',
            field=models.CharField(default=1, max_length=12, verbose_name='Confirme a senha de acesso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='escola',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Este e-mail já está cadastrada em nosso sistema.'}, max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='telefone_escola',
            field=models.CharField(error_messages={'unique': 'Este número de telefone já existe em nosso sistema. Verifique e tente novamente.'}, max_length=12, unique=True, verbose_name='Número de Telefone'),
        ),
    ]
