# Generated by Django 2.2.4 on 2019-08-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190808_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parceiro',
            name='data_mensagem',
        ),
        migrations.RemoveField(
            model_name='parceiro',
            name='telefone_parceiro',
        ),
        migrations.AddField(
            model_name='parceiro',
            name='assunto_mensagem',
            field=models.CharField(default=1, max_length=255, verbose_name='Assunto da mensagem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='escola',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Este e-mail já está cadastrado em nosso sistema.'}, max_length=255, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='nome_escola',
            field=models.CharField(error_messages={'unique': 'Escola com este nome já está cadastrado em nosso sistema.'}, max_length=255, unique=True, verbose_name='Nome da Escola'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='mensagem_parceiro',
            field=models.TextField(verbose_name='Escreva sua mensagem'),
        ),
    ]
