# Generated by Django 2.2.4 on 2019-08-09 15:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20190808_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='data_mensagem',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 15, 28, 9, 670099, tzinfo=utc), verbose_name='date_created'),
        ),
    ]
