# Generated by Django 2.2.4 on 2019-08-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_contato_data_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_mensagem',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
    ]
