# Generated by Django 2.2.4 on 2019-08-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20190809_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='telefone_escola',
            field=models.CharField(max_length=12, verbose_name='Número de Telefone'),
        ),
    ]
