# Generated by Django 2.2.4 on 2019-08-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20190810_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='telefone_escola',
            field=models.CharField(error_messages={'unique': 'Este número de telefone já existe em nosso sistema. Verifique e tente novamente.'}, max_length=12, unique=True, verbose_name='Número de Telefone'),
        ),
    ]
