# Generated by Django 2.2.4 on 2019-08-15 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20190815_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Escola'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='idade_aluno',
            field=models.CharField(max_length=2, verbose_name='Idade do Aluno'),
        ),
    ]
