# Generated by Django 2.2.4 on 2019-08-15 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20190815_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='escola',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='website.Escola'),
        ),
    ]
