# Generated by Django 2.2.4 on 2019-08-17 01:13

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20190816_2128'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='aluno',
            managers=[
                ('estudante', django.db.models.manager.Manager()),
            ],
        ),
    ]
