# Generated by Django 2.2.4 on 2019-08-19 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20190816_2213'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='aluno',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='aluno',
            name='escola',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Escola'),
            preserve_default=False,
        ),
    ]
