# Generated by Django 2.2.4 on 2019-08-19 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20190816_2213'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='aluno',
            managers=[
            ],
        ),
    ]
