# Generated by Django 2.2.4 on 2019-08-19 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20190819_1235'),
        ('website', '0022_auto_20190818_2338'),
    ]

    operations = [
    ]
